### ISSUE TITLE
letter emojis not visible, being shown as :x_color:

### ISSUE THREAD

**Issue by DetachHead** [vidhanio/discordle#1]
![image](https://user-images.githubusercontent.com/57028336/151323721-c955f13a-d585-4ff6-9a3f-f942e71abb54.png)

**Comment by vidhanio** [comment]
Hi!

I think this bug comes from the roles the bot has not being able to send
external emojis. Could you try giving @ everyone the ability to post
external emojis?

**Comment by DetachHead** [comment]
i just gave it the permission and it didn't seem to fix the issue

**Comment by vidhanio** [comment]
This was really weird, and it happened in another server as well, but doesn't happen in others. I am 100% sure it is some permission issue, could you check if the bot's roles all allow it to send external emojis, as well as the channel/category?

**Comment by vidhanio** [comment]
Hey! Was this issue fixed?

**Comment by vidhanio** [comment]
Closing for now. Please feel free to re-open if your issue was not fixed. Thank you for the report!

**Comment by vidhanio** [comment]
Update, I found that this issue seems to be upstream:
https://github.com/discord/discord-api-docs/discussions/3307

The fix at the moment is to allow `@everyone` to send external emojis.
