### ISSUE TITLE
HTTP 401 Unauthorized errors

### ISSUE THREAD

**Issue by Droobert** [vidhanio/discordle#6]
Issue: I will sometimes get 401 errors and this locks me out of making guesses. I believe it is related to letting the puzzle sit for awhile before making my next guess? If I put in rapid fire guesses and quickly finish the puzzle I seem to avoid errors but if I let it sit for like 30 minutes or longer between guesses it errors out. I'll try letting a couple more puzzles sit for awhile to see if I can reproduce it consistently.

Example:
![image](https://user-images.githubusercontent.com/12676527/151719134-13e5ba72-6c75-4476-923f-fcf58a8715ce.png)

**Comment by vidhanio** [comment]
This is likely caused by webhooks not being able to be updated after long periods of time. I will probably add a timeout feature if a wordle has not been used in 30 minutes.

**Comment by Droobert** [comment]
Yeah if it has to time out then at least telling the user what happened sounds like some some good quality of life.
