### ISSUE TITLE
Guild Letters says "No wordle in progress."

### ISSUE THREAD

**Issue by Droobert** [vidhanio/discordle#7]
Issue: There is a guild wordle started and multiple users have been able to use /guild guess but for some reason using /guild letters throws the message "No wordle in progress." for each user that tries it. I have been able to get the command to work sometimes but the command seems to fail often. Trying to narrow down what causes it to fail.

Example:
![image](https://user-images.githubusercontent.com/12676527/151721247-05db2b01-d7e5-426e-9cc0-fe8eafb0e772.png)

![image](https://user-images.githubusercontent.com/12676527/151721306-aec077a9-831b-4da4-af77-392b57077500.png)

**Comment by vidhanio** [comment]
Odd. Does it work sometimes?

**Comment by vidhanio** [comment]
AH I found the bug. It will be fixed on next release, just away from computer at the moment. Thank you very much for the report!

**Comment by Droobert** [comment]
Sweet, glad it was easy to find!

**Comment by vidhanio** [comment]
https://github.com/vidhanio/diswordle/releases/tag/v1.4.1 should fix this.

The deployment should restart the bot in a few minutes. :)

**Comment by vidhanio** [comment]
Seems to be working. Thank you so much for the bug-hunting, and feel free to re-open if the issue pops up again.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/41439633/151726499-eb57c963-f978-4127-a1b9-e293691cae1d.png">

**Comment by Droobert** [comment]
Awesome, thanks for the quick fix!
